apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agrimarket.fullname" . }}-nginx
  labels:
    {{- include "agrimarket.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "agrimarket.selectorLabels" . | nindent 6 }}
      component: nginx
  template:
    metadata:
      labels:
        {{- include "agrimarket.selectorLabels" . | nindent 8 }}
        component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
