apiVersion: v1
kind: Service
metadata:
  name: {{ include "agrimarket.fullname" . }}-nginx
  labels:
    {{- include "agrimarket.labels" . | nindent 4 }}
    component: nginx
spec:
  type: {{ .Values.nginxService.type }}
  ports:
    - port: {{ .Values.nginxService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agrimarket.selectorLabels" . | nindent 4 }}
    component: nginx
