apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agrimarket.fullname" . }}-secret
  labels:
    {{- include "agrimarket.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.databaseUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
